#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const outPath = join(root, "src", "version.ts");
const pluginPath = join(root, ".claude-plugin", "plugin.json");

const content = `// Auto-generated by scripts/sync-version.js — do not edit manually
export const VERSION = "${pkg.version}";
`;

writeFileSync(outPath, content);

const plugin = JSON.parse(readFileSync(pluginPath, "utf8"));
plugin.version = pkg.version;
writeFileSync(pluginPath, JSON.stringify(plugin, null, 2) + "\n");
console.log(`synced version → ${pkg.version}`);
